In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
import tensorflow as tf
import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

[]


In [2]:
x=tf.constant(np.random.randint(0,10,size=(5,4,3)))



In [3]:
x.get_shape()

TensorShape([Dimension(5), Dimension(4), Dimension(3)])

In [4]:
b=tf.transpose(x, perm=[0, 2, 1])

In [5]:
s=tf.InteractiveSession()

In [6]:
b.eval().shape   # It is very important so perm has values of dims of an array

(5, 3, 4)

In [7]:
x.eval()[:,:,0]

array([[6, 2, 4, 7],
       [8, 3, 8, 0],
       [4, 6, 1, 3],
       [5, 9, 7, 8],
       [1, 5, 9, 8]])

In [8]:
b.eval()[:,0,:]  #very important to check 

array([[6, 2, 4, 7],
       [8, 3, 8, 0],
       [4, 6, 1, 3],
       [5, 9, 7, 8],
       [1, 5, 9, 8]])

In [9]:
#With transpose and dimensions we can specify in what form do we want tensor as

In [10]:
# >>>> gather <<<< #

In [11]:
a=tf.constant(np.random.randint(0,10,size=(4,2)))

In [12]:
b=tf.gather(a,[1,3])

In [13]:
a.eval()

array([[6, 7],
       [1, 6],
       [4, 3],
       [4, 4]])

In [14]:
b.eval()

array([[1, 6],
       [4, 4]])

In [15]:
# It can be used on let say training examples satisfying particular condition
# that is we can let say take out indices of training examples where particular condition is satisfied
# and we can gather them using tf.gather

In [16]:
#but remember tf.gather gathers examples on basis of rows. It sees only first dim of the tensor.  0

In [17]:
### >> Application of gather_nd

In [18]:
data=tf.constant(np.random.randint(0,10,size=(5,6)))


In [19]:
result=tf.gather(data,[1,2])

In [20]:
result.eval()

array([[9, 5, 4, 8, 3, 9],
       [1, 5, 6, 5, 1, 4]])

In [21]:
data.eval()   # same as tf.gather

array([[2, 4, 8, 6, 5, 5],
       [9, 5, 4, 8, 3, 9],
       [1, 5, 6, 5, 1, 4],
       [3, 8, 8, 9, 2, 0],
       [8, 4, 2, 1, 8, 8]])

In [22]:
result1=tf.gather(data,[[1,2],[2,3],[3,4]])

In [23]:
result1.eval()  #### very important APPLICATION of tf.gather

array([[[9, 5, 4, 8, 3, 9],
        [1, 5, 6, 5, 1, 4]],

       [[1, 5, 6, 5, 1, 4],
        [3, 8, 8, 9, 2, 0]],

       [[3, 8, 8, 9, 2, 0],
        [8, 4, 2, 1, 8, 8]]])

In [24]:
result2=tf.gather_nd(data,[[1,2],[3,4]])

In [25]:
result2.eval()   ### [[x1,x2],[y1,y2]]  gives (x1,y1) element and (x2,y2) element of data

array([4, 2])

In [26]:
data1=tf.constant(np.random.randint(10,size=(5,4,3)))
result3=tf.gather_nd(data1,[[1,1,1],[2,2,2]])

In [27]:
result3.eval()

array([2, 1])

In [28]:
data1.eval()[1,1,1]

2

In [29]:
data1.eval()[2,2,2]

1