In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

[]


In [2]:
a=tf.fill([3,4],9)

In [3]:
s=tf.InteractiveSession()


In [4]:
a.eval()

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=int32)

In [5]:
b=tf.random_uniform(shape=[],minval=0,maxval=65535)

In [6]:
print(b.eval())
batchsize=400
MAX=65535

30558.104


In [7]:
c=tf.fill([batchsize],tf.random_uniform(shape=[],minval=0,maxval=MAX))

In [8]:
c.eval()

array([57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237.61,
       57237.61, 57237.61, 57237.61, 57237.61, 57237.61, 57237

In [9]:
c.get_shape()

TensorShape([Dimension(400)])

In [10]:
d=tf.random_uniform(shape=[batchsize],minval=0,maxval=batchsize)
d.eval()

array([5.51133652e+01, 1.91441971e+02, 3.33225067e+02, 1.39114471e+02,
       1.61118362e+02, 8.27244720e+01, 1.05472755e+02, 1.24766304e+02,
       2.24886078e+02, 4.42395210e+00, 1.74648621e+02, 3.18426361e+02,
       6.24266624e+01, 2.05895660e+02, 3.53171387e+02, 2.61124084e+02,
       3.37008179e+02, 7.83230743e+01, 3.25635452e+01, 2.75080261e+02,
       3.87356903e+02, 6.18932724e+01, 2.01927368e+02, 1.47522018e+02,
       2.91608521e+02, 3.86776123e+02, 1.11204674e+02, 3.60450165e+02,
       2.97234058e+01, 9.18644867e+01, 2.03038406e+02, 2.36620621e+02,
       2.24335190e+02, 2.56995148e+02, 2.82879211e+02, 1.97248596e+02,
       5.21537323e+01, 1.45815231e+02, 3.47660583e+02, 3.75687073e+02,
       1.29729843e+02, 2.95721924e+02, 2.62135895e+02, 8.13136597e+01,
       3.34352493e+01, 2.28096481e+02, 5.95202446e+00, 2.16054489e+02,
       1.51596878e+02, 2.02078819e+01, 6.70182190e+01, 2.23638016e+02,
       1.65667297e+02, 1.60084106e+02, 4.41731453e+01, 2.93524597e+02,
      

In [11]:
d.get_shape()

TensorShape([Dimension(400)])

In [12]:
tf.stack([c,d])

<tf.Tensor 'stack:0' shape=(2, 400) dtype=float32>

In [13]:
c.get_shape()

TensorShape([Dimension(400)])

In [14]:
d.get_shape()

TensorShape([Dimension(400)])

In [15]:
e=tf.transpose(tf.stack([c,d]))

In [16]:
e.eval().shape

(400, 2)

In [17]:
a=tf.constant(np.random.randint(0,10,size=[5,4,3]))
b=tf.constant(np.random.randint(0,10,size=[5,4,3]))

In [18]:
a.get_shape()
b.get_shape()

TensorShape([Dimension(5), Dimension(4), Dimension(3)])

In [19]:
tf.stack([a,b])

<tf.Tensor 'stack_2:0' shape=(2, 5, 4, 3) dtype=int64>

In [20]:
a=np.random.randint(0,10,size=[5,4,3])
b=np.random.randint(0,10,size=[5,4,3])
c=np.random.randint(0,10,size=[5,4,3])
d=np.random.randint(0,10,size=[5,4,3])

In [21]:
e=np.stack([a,b,c,d],axis=0)

In [22]:
e[0]

array([[[2, 9, 0],
        [0, 2, 9],
        [7, 8, 4],
        [0, 3, 4]],

       [[5, 3, 9],
        [3, 0, 7],
        [4, 5, 1],
        [9, 5, 9]],

       [[9, 7, 4],
        [9, 5, 4],
        [6, 6, 4],
        [2, 6, 2]],

       [[2, 5, 4],
        [7, 7, 7],
        [4, 5, 2],
        [9, 0, 5]],

       [[5, 0, 5],
        [9, 9, 5],
        [0, 3, 9],
        [7, 3, 2]]])

In [23]:
a

array([[[2, 9, 0],
        [0, 2, 9],
        [7, 8, 4],
        [0, 3, 4]],

       [[5, 3, 9],
        [3, 0, 7],
        [4, 5, 1],
        [9, 5, 9]],

       [[9, 7, 4],
        [9, 5, 4],
        [6, 6, 4],
        [2, 6, 2]],

       [[2, 5, 4],
        [7, 7, 7],
        [4, 5, 2],
        [9, 0, 5]],

       [[5, 0, 5],
        [9, 9, 5],
        [0, 3, 9],
        [7, 3, 2]]])

In [24]:
# Above Example we were stacking 3D tensors
# what if we stack 2D tensors

In [25]:
a=np.random.randint(0,10,size=[5,4])
b=np.random.randint(0,10,size=[5,4])
c=np.random.randint(0,10,size=[5,4])
d=np.random.randint(0,10,size=[5,4])

In [26]:
tf.stack([a,b,c,d],axis=-1).eval().shape   #very important stacking is only possible when we have all tensors of same dims

(5, 4, 4)

In [27]:
# >>>>>>>>>>>>>>> Tensorflow Squeeze <<<<<<<<<<<<<<<<<< #
a=tf.constant(np.random.randint(0,10,size=[1,1,2,1,3,1,1]))

In [28]:
b=tf.squeeze(a)

In [29]:
b.eval().shape   # very important

(2, 3)